repos:

  # -------------------------
  # Flake8 linter
  # -------------------------
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=100
          - --ignore=E126,E203,W503,E501
          - --exclude=.venv,__pycache__,build,dist

  # -------------------------
  # Optional hygiene hooks
  # -------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
