from domain.keyword_config import KeywordConfig

KEYWORD_CONFIG: dict[str, KeywordConfig] = {
    "cat": KeywordConfig(
        query_include=[
            "cat",
            "cats",
            "kitten",
            "kittens",
            "cat shorts",
            "funny cat",
            "funny cats",
            "cat videos",
            "shorts",
        ],
        query_exclude=["catfish", "catfishing", "caterpillar", "scan"],
        thumbnail_emojis=["😺", "🐾", "😻"],
        title_emojis=["😺"],
        description_emojis=["🐾"],
        tags=["cat", "cats", "cat shorts", "funny cats", "cute animals"],
        hashtags=["#cat", "#cats", "#catshorts", "#funnycats", "#cute"],
    ),
    "funny": KeywordConfig(
        query_include=["funny"],
        query_exclude=[],
        thumbnail_emojis=["😂", "🤣", "😹"],
        title_emojis=["😂"],
        description_emojis=["🤣"],
        tags=["funny", "funny videos", "try not to laugh", "comedy"],
        hashtags=["#funny", "#comedy", "#lol", "#viral"],
    ),
    "gaming": KeywordConfig(
        query_include=[],
        query_exclude=[],
        thumbnail_emojis=["🎮", "🔥", "💥"],
        title_emojis=["🎮"],
        description_emojis=["🔥"],
        tags=["gaming", "gaming shorts", "funny gaming", "viral gaming"],
        hashtags=["#gaming", "#gamingshorts", "#gamer", "#viral"],
    ),
    "dogs": KeywordConfig(
        query_include=[],
        query_exclude=[],
        thumbnail_emojis=["🐶", "🐾", "❤️"],
        title_emojis=["🐶"],
        description_emojis=["🐾"],
        tags=["dogs", "dog shorts", "funny dogs", "cute dogs"],
        hashtags=["#dogs", "#dogshorts", "#funnypets", "#cute"],
    ),
    "fails": KeywordConfig(
        query_include=[],
        query_exclude=[],
        thumbnail_emojis=["💥", "😬", "🤣"],
        title_emojis=["💥"],
        description_emojis=["🤣"],
        tags=["fails", "funny fails", "epic fails", "fail compilation"],
        hashtags=["#fails", "#epicfail", "#funnyfails"],
    ),
    "satisfying": KeywordConfig(
        query_include=[],
        query_exclude=[],
        thumbnail_emojis=["✨", "🧼", "👌"],
        title_emojis=["✨"],
        description_emojis=["👌"],
        tags=["satisfying", "oddly satisfying", "relaxing videos"],
        hashtags=["#satisfying", "#oddlysatisfying", "#relaxing"],
    ),
    "memes": KeywordConfig(
        query_include=[],
        query_exclude=[],
        thumbnail_emojis=["🧠", "🤣", "🔥"],
        title_emojis=["🤣"],
        description_emojis=["🔥"],
        tags=["memes", "viral memes", "internet memes"],
        hashtags=["#memes", "#viral", "#internetmemes"],
    ),
}
